
#
# Prepares Vina output for input into Pafnucy prepare.py.
# Reads in docked poses generated by Vina, saves first mode (highest binding affinity) as ligand.mol2; save 20angstrom residue
# box centered at ligand as pocket.mol2
#
from pymol import cmd, stored
import os


def get_ligand( ligand_path ):
    '''
DESCRIPTION

    Reads in docked poses generated by Vina, saves first mode (highest binding affinity) as ligand.mol2
    '''
    base = os.path.basename(ligand_path)
    FILENAME = os.path.splitext(base)[0]

    #print "Loading %s\n", % (ligand_path)
    cmd.load(ligand_path) # load "C:/Users/Janet Liu/Documents/2019-2020/CS221/Project/data_files/stx_hnav1-7/ligand_out.pdbqt"
    cmd.split_states(FILENAME)
    cmd.save(os.path.dirname(ligand_path)+"/ligand.mol2", FILENAME+"_0001", -1, 'mol2')

def get_pocket( protein_path, ligand_path ):
    '''
DESCRIPTION

    Creates 20-angstrom box centered at geometric center of docked ligand, saves object as pocket.mol2
    '''
    base_ligand = os.path.basename(ligand_path)
    FILENAME_LIG = os.path.splitext(base_ligand)[0]
    base_protein = os.path.basename(protein_path)
    FILENAME_PRO = os.path.splitext(base_protein)[0]


    cmd.load(ligand_path) # Should use the .mol2 file generated by get_ligand
    cmd.load(protein_path)
    cmd.select(name="sele", selection="br. all near_to 20 of ligand")
    cmd.create("pocket", "sele")
    cmd.save(os.path.dirname(protein_path)+"/pocket.mol2", "pocket", -1, 'mol2')


cmd.extend( "get_ligand", get_ligand );
cmd.extend( "get_pocket", get_pocket);

