#
# Prepares Vina output for input into Pafnucy prepare.py.
# Reads in docked poses generated by Vina, saves first mode (highest binding affinity) as ligand.mol2; save 20angstrom residue
# box centered at ligand as pocket.mol2
#
from pymol import cmd, stored
import os

def get_ligand( ligand_path ):
    '''
DESCRIPTION

    Reads in docked poses generated by Vina, saves first mode (highest binding affinity) as ligand.mol2
    '''
    base = os.path.basename(ligand_path)
    FILENAME = os.path.splitext(base)[0]

    print "Loading %s ..." % (ligand_path)
    load ligand_path # load "C:/Users/Janet Liu/Documents/2019-2020/CS221/Project/data_files/stx_hnav1-7/ligand_out.pdbqt"
    split states FILENAME
    save os.path.dirname(ligand_path)+"/ligand.mol2", FILENAME+"_0001"

def get_pocket( protein_path, ligand_out_path ):
    '''
DESCRIPTION

    Creates 20-angstrom box centered at geometric center of docked ligand, saves object as pocket.mol2
    '''
    base_ligand = os.path.basename(ligand_out_path)
    FILENAME_LIG = os.path.splitext(base_ligand)[0]
    base_protein = os.path.basename(protein_path)
    FILENAME_PRO = os.path.splitext(base_protein)[0]


    load ligand_out_path # Should use the .mol2 file generated by get_ligand
    load protein_path
    select br. all near_to 20 of FILENAME_LIG
    extract pocket, sele
    save os.path.dirname(protein_path)+"/pocket.mol2"


cmd.extend( "get_ligand", get_ligand );
cmd.extend( "get_pocket", get_pocket);

